### ISSUE TITLE
TypeError: in method 'PCB_TRACK_SetStart', argument 2 of type 'VECTOR 2I const &'

### ISSUE THREAD

**Issue by nm17** [mitxela/kicad-round-tracks#13]
## Traceback
```
Traceback (most recent call last): 
 File "/home/nm17/local/share/kicad/6.99/3rdparty/plugins/com_github_mitxela_kicad-round-tracks/round_tracks_action.py", line 87, in run
   self.addIntermediateTracks(self.board, scaling = classes[classname]['scaling'], netclass = classname, native = True, onlySelection = anySelected, avoid_junctions = avoid)
 File "/home/nm17/local/share/kicad/6.99/3rdparty/plugins/com_github_mitxela_kicad-round-tracks/round_tracks_action.py", line 255, in addintermediateTracks
   reverseTrack(t1)
 File "/home/nm17/local/share/kicad/6.99/3rdparty/plugins/com_github_mitxela_kicad-round-tracks/round_tracks_utils.py", line 14, in reverseTrack
  t1.SetStart(ep)
 File "/usr/lib/kicad-nightly/lib/python3/dist-packages/pcbnew.py", line 15781, in SetStart
  return _pcbnew.PCB_TRACK_SetStart(self, start)
TypeError: in method 'PCB_TRACK_SetStart', argument 2 of type 'VECTOR 2I const &'
```

## Version info
```
Application: KiCad

Version: 6.99.0-unknown-c34fb494b1~148~ubuntu22.04.1, release build

Libraries:
	wxWidgets 3.0.5
	FreeType 2.11.1
	HarfBuzz 2.7.4
	FontConfig 2.13.1
	libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.11

Platform: Linux 5.15.0-27-generic x86_64, 64 bit, Little endian, wxGTK, ubuntu, x11

Build Info:
	Date: May  2 2022 09:07:37
	wxWidgets: 3.0.5 (wchar_t,wx containers,compatible with 2.8) GTK+ 3.24
	Boost: 1.74.0
	OCC: 7.5.2
	Curl: 7.81.0
	ngspice: 36
	Compiler: GCC 11.2.0 with C++ ABI 1016

Build settings:
	KICAD_USE_OCC=ON
	KICAD_SPICE=ON
```

**Comment by mitxela** [comment]
KiCad nightly is not supported, sorry. See https://github.com/mitxela/kicad-round-tracks/issues/7

**Comment by nm17** [comment]
Thank you!
