### ISSUE TITLE
Not working in KiCad 7 on Mac

### ISSUE THREAD

**Issue by airiclenz** [mitxela/kicad-round-tracks#23]
Hello, version 7 of KiCad seems to have broken the plugin. I am receiving this error message on a mac:

```
Traceback (most recent call last):

File "/Users/username/Documents/KiCad/7.0/3rdparty/plugins/com_github_mitxela_kicad-round-tracks/round_tracks_action.py", line 378, in Run
rt = RoundTracks(board, self)

File "/Users/username/Documents/KiCad/7.0/3rdparty/plugins/com_github_mitxela_kicad-round-tracks/round_tracks_action.py", line 56, in __init__
for class_id in self.board.GetDesignSettings().GetNetClasses().NetClasses():

AttributeError: 'BOARD_DESIGN_SETTINGS' object has no attribute 'GetNetClasses'
```

**Comment by airiclenz** [comment]
...saw that this was already posten and answered here: https://github.com/mitxela/kicad-round-tracks/issues/22
Closing it - Thanks Mitxela!

**Comment by airiclenz** [comment]
closed.
